OPENAI_KEY = "OPENAI_KEY"
OPENAI_MODEL = "OPENAI_MODEL"
TOTAL_QUES  = "TOTAL_QUES"
SUPABASE_KEY = "SUPABASE_KEY"
SUPABASE_URL = "SUPABASE_URL"
COHERE_API_KEY = "COHERE_API_KEY"
AWS_ACCESS_KEY = "AWS_ACCESS_KEY"
AWS_SECRET_KEY = "AWS_SECRET_KEY"